import 'package:flutter/material.dart';

class CategoriesProvider extends ChangeNotifier {
  final List<String> _categories = [
    "Pizza",
    "Dessert",
    "Wine",
    "Frappe",
    "Milkshakes",
    "Lemonades",
    "Coffee",
    "Long Cocktails",
    "Short Cocktails",
    "Capis Cocktails",
    "Long Drinks",
    "NA Cocktails",
    "Shots",
    "Spirits",
    "Hot Drinks",
    "Coffee Cocktails",
    "Ice Coffee",
    "Hot Chocolate",
    "Tea",
    "Beers",
  ];

  final Map<String, String> _menu ={
    'QUATTRO FORMAGGI TARTUFO': 'Pizza',
    'TRE CARNI': 'Pizza',
    'QUATTRO FORMAGGI SALAMI': 'Pizza',
    'QUATRO STAGIONI': 'Pizza',
    'QUATTRO FORMAGGI': 'Pizza',
    'COTTO E FUNGHI': 'Pizza',
    'SALAMI DOLCE': 'Pizza',
    'DIAVOLA': 'Pizza',
    'MARGHERITA': 'Pizza',
    'FOCACCIA': 'Pizza',
    'SOS DULCE': 'Pizza',
    'SOS PICANT': 'Pizza',
    'CARMELINA LETCHE': 'Dessert',
    'ORANGE MOUSSE': 'Dessert',
    'LAVA CAKE CU INGHETATA': 'Dessert',
    'P Proseco': 'Wine',
    'P Vin alb': 'Wine',
    'P Vin roze': 'Wine',
    'P Vin rosu': 'Wine',
    'Sex on the Beach': 'Long Cocktails',
    'PINA COLADA': 'Long Cocktails',
    'APEROL SPRITZ': 'Long Cocktails',
    'MOJITO': 'Long Cocktails',
    'MAI TAI': 'Long Cocktails',
    'LONG ISLAND ICED TEA': 'Long Cocktails',
    'CAMPARI SPRITZ': 'Long Cocktails',
    'STRAWBERRY MOJITO': 'Long Cocktails',
    'RASPBERRY MOJITO': 'Long Cocktails',
    'BLUEBERRY MOJITO': 'Long Cocktails',
    'TEQUILA SUNRISE': 'Long Cocktails',
    'Moscow Mule': 'Long Cocktails',
    'WHISKY SOUR': 'Short Cocktails',
    'MIMOSA': 'Short Cocktails',
    'COSMOPOLITAN': 'Short Cocktails',
    'VODKA SOUR': 'Short Cocktails',
    'BLACK RUSIAN': 'Short Cocktails',
    'GODMOTHER': 'Short Cocktails',
    'GODFATHER': 'Short Cocktails',
    'MARGARITA': 'Short Cocktails',
    'WHITE RUSIAN': 'Short Cocktails',
    'ORGASM': 'Short Cocktails',
    'Negroni': 'Short Cocktails',
    'STRAWBERRY CAPIROSKA': 'Capis Cocktails',
    'CAPIRITA': 'Capis cocktails',
    'CAPIRISIMA': 'Capis Cocktails',
    'CAPIROSKA': 'Capis Cocktails',
    'WHISKY COLA': 'Long Drinks',
    'WHISKY ENERGY': 'Long Drinks',
    'CUBA LIBRE': 'Long Drinks',
    'GIN TONIC': 'Long Drinks',
    'CAMPARI ORANGE': 'Long Drinks',
    'VODKA APPLE': 'Long Drinks',
    'JAGER ENERGY': 'Long Drinks',
    'SCREWDRIVER': 'Long Drinks',
    'CAPE CODER': 'Long Drinks',
    'VODKA TONIC': 'Long Drinks',
    'STRAWBERRY KISS': 'NA Cocktails',
    'BLUE MOON': 'NA Cocktails',
    'GREEN APPLE': 'NA Cocktails',
    'SAFE SEX ON THE BEACH': 'NA Cocktails',
    'CHERRY TONIC': 'NA Cocktails',
    'VIRGIN COLADA': 'NA Cocktails',
    'KAMIKAZE': 'Shots',
    'BLOWJOB': 'Shots',
    'JAGERMEISTER Shot': 'Shots',
    'VODKA': 'Shots',
    'TEQUILA': 'Shots',
    'BRAIN DAMAGE': 'Shots',
    'METRU SHOTS': 'Shots',
    'BAILEYS': 'Spirits',
    'KAHLUA': 'Spirits',
    'DISARONNO AMARETTO': 'Spirits',
    'PIGS NOSE WISKY': 'Spirits',
    'ARCHER PEACH': 'Spirits',
    'STALINSKAYA BLUE': 'Spirits',
    'JACK DANIELS': 'Spirits',
    'SMOKEHEAD': 'Spirits',
    'STALINSKAYA SILVER': 'Spirits',
    'CHIVAS REGAL': 'Spirits',
    'WEMBLEY': 'Spirits',
    'OLD PASCAS': 'Spirits',
    'SIERRA TEQUILA': 'Spirits',
    'APEROL': 'Spirits',
    'CAMPARI': 'Spirits',
    'JAGERMEISTER': 'Spirits',
    'CINZANO BIANCO': 'Spirits',
    'CUTTY SARK WHISKY': 'Spirits',
    'CINZANO ROSSO': 'Spirits',
    'GRAND PASSION VS': 'Spirits',
    'Captain Morgan Black': 'Spirits',
    'CAPTAIN MORGAN SPICED': 'Spirits',
    'LAPTE CU SCORTISIOARA': 'Hot Drinks',
    'VIN FIERT': 'Hot Drinks',
    'OREO Frappe': 'Frappe',
    'CARAMELFrappe': 'Frappe',
    'CIOCOLATA Frappe': 'Frappe',
    'VANILIE Frappe': 'Frappe',
    'CARAMEL': 'Milkshakes',
    'VANILIE': 'Milkshakes',
    'CIOCOLATA': 'Milkshakes',
    'OREO': 'Milkshakes',
    'MOJITO Lemonade': 'Lemonades',
    'CLASICA': 'Lemonades',
    'CU AROME': 'Lemonades',
    'DOUBLE ESPRESSO': 'Coffee',
    'IRISH LATTE': 'Coffee',
    'ESPRESSO': 'Coffee',
    'AMERICANO': 'Coffee',
    'CAPPUCCINO': 'Coffee',
    'CREME BRULEE LATTE': 'Coffee',
    'CAFFEE MOCHA': 'Coffee',
    'CAFFE LATTE': 'Coffee',
    'WHITE CHOCOLATE MOCHA': 'Coffee',
    'CARAMEL LATTE': 'Coffee',
    'AMARETTO COFFE': 'Coffee Cocktails',
    'FRENCH COFFEE': 'Coffee Cocktails',
    'BAILEYS COFFEE': 'Coffee Cocktails',
    'IRISH COFFEE': 'Coffee Cocktails',
    'ICE CARAMEL MACHIATO': 'Ice Coffee',
    'ICE COFEE': 'Ice Coffee',
    'LATTE FREDDO': 'Ice Coffee',
    'ALBA': 'Hot Chocolate',
    'NEAGRA': 'Hot Chocolate',
    'DENSA': 'Hot Chocolate',
    'INFUZIE': 'Tea',
    'CEAI': 'Tea',
    'METRU DE BERE': 'Beers',
    'FRANZISKANER BLOND': 'Beers',
    'CARAIMAN': 'Beers',
    'BUCUR BLONDA': 'Beers',
    'LEFFE BLOND': 'Beers',
    'LEFFE BRUN': 'Beers',
    'CORONA': 'Beers',
    'STRONGBOW GOLD': 'Beers',
    'STRONGBOW RED': 'Beers',
    'STELLA ARTOIS': 'Beers',
    'STELA ARTOIS FARA ALCOOL': 'Beers',
    'BECKS': 'Beers',
    'STAROPRAMEN': 'Beers',
  };

  String _selectedCategory = '';

  List<String> get categories => _categories;
  Map<String, String> get menu => _menu;
  String get selectedCategory => _selectedCategory;

  void setCategory(String categoryName) {
    _selectedCategory = categoryName;
    notifyListeners();
  }
}
