import 'package:flutter/material.dart';

class CountsProvider extends ChangeNotifier {
  final Map<String, int> _menuItemsCount = {
    'QUATTRO FORMAGGI TARTUFO': 0,
    'TRE CARNI': 0,
    'QUATTRO FORMAGGI SALAMI': 0,
    'QUATRO STAGIONI': 0,
    'QUATTRO FORMAGGI': 0,
    'COTTO E FUNGHI': 0,
    'SALAMI DOLCE': 0,
    'DIAVOLA': 0,
    'MARGHERITA': 0,
    'FOCACCIA': 0,
    'SOS DULCE': 0,
    'SOS PICANT': 0,
    'CARMELINA LETCHE': 0,
    'ORANGE MOUSSE': 0,
    'LAVA CAKE CU INGHETATA': 0,
    'P Proseco': 0,
    'P Vin alb': 0,
    'P Vin roze': 0,
    'P Vin rosu': 0,
    'Sex on the Beach': 0,
    'PINA COLADA': 0,
    'APEROL SPRITZ': 0,
    'MOJITO': 0,
    'MAI TAI': 0,
    'LONG ISLAND ICED TEA': 0,
    'CAMPARI SPRITZ': 0,
    'STRAWBERRY MOJITO': 0,
    'RASPBERRY MOJITO': 0,
    'BLUEBERRY MOJITO': 0,
    'TEQUILA SUNRISE': 0,
    'Moscow Mule': 0,
    'WHISKY SOUR': 0,
    'MIMOSA': 0,
    'COSMOPOLITAN': 0,
    'VODKA SOUR': 0,
    'BLACK RUSIAN': 0,
    'GODMOTHER': 0,
    'GODFATHER': 0,
    'MARGARITA': 0,
    'WHITE RUSIAN': 0,
    'ORGASM': 0,
    'Negroni': 0,
    'STRAWBERRY CAPIROSKA': 0,
    'CAPIRITA': 0,
    'CAPIRISIMA': 0,
    'CAPIROSKA': 0,
    'WHISKY COLA': 0,
    'WHISKY ENERGY': 0,
    'CUBA LIBRE': 0,
    'GIN TONIC': 0,
    'CAMPARI ORANGE': 0,
    'VODKA APPLE': 0,
    'JAGER ENERGY': 0,
    'SCREWDRIVER': 0,
    'CAPE CODER': 0,
    'VODKA TONIC': 0,
    'STRAWBERRY KISS': 0,
    'BLUE MOON': 0,
    'GREEN APPLE': 0,
    'SAFE SEX ON THE BEACH': 0,
    'CHERRY TONIC': 0,
    'VIRGIN COLADA': 0,
    'KAMIKAZE': 0,
    'BLOWJOB': 0,
    'JAGERMEISTER Shot': 0,
    'VODKA': 0,
    'TEQUILA': 0,
    'BRAIN DAMAGE': 0,
    'METRU SHOTS': 0,
    'BAILEYS': 0,
    'KAHLUA': 0,
    'DISARONNO AMARETTO': 0,
    'PIGS NOSE WISKY': 0,
    'ARCHER PEACH': 0,
    'STALINSKAYA BLUE': 0,
    'JACK DANIELS': 0,
    'SMOKEHEAD': 0,
    'STALINSKAYA SILVER': 0,
    'CHIVAS REGAL': 0,
    'WEMBLEY': 0,
    'OLD PASCAS': 0,
    'SIERRA TEQUILA': 0,
    'APEROL': 0,
    'CAMPARI': 0,
    'JAGERMEISTER': 0,
    'CINZANO BIANCO': 0,
    'CUTTY SARK WHISKY': 0,
    'CINZANO ROSSO': 0,
    'GRAND PASSION VS': 0,
    'Captain Morgan Black': 0,
    'CAPTAIN MORGAN SPICED': 0,
    'LAPTE CU SCORTISIOARA': 0,
    'VIN FIERT': 0,
    'OREO Frappe': 0,
    'CARAMELFrappe': 0,
    'CIOCOLATA Frappe': 0,
    'VANILIE Frappe': 0,
    'CARAMEL': 0,
    'VANILIE': 0,
    'CIOCOLATA': 0,
    'OREO': 0,
    'MOJITO Lemonade': 0,
    'CLASICA': 0,
    'CU AROME': 0,
    'DOUBLE ESPRESSO': 0,
    'IRISH LATTE': 0,
    'ESPRESSO': 0,
    'AMERICANO': 0,
    'CAPPUCCINO': 0,
    'CREME BRULEE LATTE': 0,
    'CAFFEE MOCHA': 0,
    'CAFFE LATTE': 0,
    'WHITE CHOCOLATE MOCHA': 0,
    'CARAMEL LATTE': 0,
    'AMARETTO COFFE': 0,
    'FRENCH COFFEE': 0,
    'BAILEYS COFFEE': 0,
    'IRISH COFFEE': 0,
    'ICE CARAMEL MACHIATO': 0,
    'ICE COFEE': 0,
    'LATTE FREDDO': 0,
    'ALBA': 0,
    'NEAGRA': 0,
    'DENSA': 0,
    'INFUZIE': 0,
    'CEAI': 0,
    'METRU DE BERE': 0,
    'FRANZISKANER BLOND': 0,
    'CARAIMAN': 0,
    'BUCUR BLONDA': 0,
    'LEFFE BLOND': 0,
    'LEFFE BRUN': 0,
    'CORONA': 0,
    'STRONGBOW GOLD': 0,
    'STRONGBOW RED': 0,
    'STELLA ARTOIS': 0,
    'STELA ARTOIS FARA ALCOOL': 0,
    'BECKS': 0,
    'STAROPRAMEN': 0,
  };

  Map<String, int> get menuItemsCount => _menuItemsCount;

  void incrementCounter(String item) {
    menuItemsCount[item] = (_menuItemsCount[item] ?? 0) + 1;
    notifyListeners();
  }

  Map<String, int> getSelectedItems() {
    return Map.fromEntries(
        _menuItemsCount.entries.where((entry) => entry.value > 0));
  }

  void resetCounts() {
    _menuItemsCount.updateAll((key, value) => 0);
    notifyListeners();
  }
}
